config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'

  get '/sign-in', to: 'sessions#new', as: :sign_in
  post '/sign-in', to: 'sessions#create'

  # When OAuth fails
  get '/auth/failure' => 'sessions#failure_oauth', :as => :oauth_failure
  # No longer provided by Omniauth, since starting the Request phase requires a POST
  get '/auth/:provider', to: redirect('/dashboard')
  # Start the OAuth callback phase
  get '/auth/:provider/callback', to: 'sessions#create_oauth'

  get '/sign-out', to: 'sessions#destroy', as: :sign_out
  delete '/sign-out', to: 'sessions#destroy'

  resource :github_webhooks, only: :create, defaults: {formats: :json}

  get :dashboard, to: redirect('/repos')

  namespace :api, default: {format: 'json'} do
    get 'gimme/error', to: 'error#server_error'
    get 'gimme/bad-json', to: 'error#bad_json'
    get 'availableRepos', to: 'available_repos#index'
    get 'repos', to: 'repos#index'
    post 'repos/:repo_type/:owner_name/:repo_name', to: 'repos#create', constraints: {type: /gh/, repo_name: /[0-z.\-]+/}
    get 'repos/:repo_type/:owner_name/:repo_name', to: 'repos#show', constraints: {type: /gh/, repo_name: /[0-z.\-]+/}
    patch 'repos/:repo_type/:owner_name/:repo_name', to: 'repos#update', constraints: {type: /gh/, repo_name: /[0-z.\-]+/}
    get '*url' => 'error#not_found', :as => :not_found
  end

  get '*url' => 'pages#app', :as => :app
end

app/views/layouts/_sentry.html.erb
<% if Rails.configuration.x.sentry.present? && Rails.configuration.x.sentry.javascript_dsn.present? %>
  <script type='text/javascript'>
    window.SentryConfig = {
      dsn: '<%= Rails.configuration.x.sentry['javascript_dsn'] %>',
      environment: '<%= ENV['RAILS_ENV'] %>',
      release: '<%= ApplicationRelease.current %>',
      xhrUrlIgnorePattern: /smartlook|mixpanel|google-analytics/,
      user: <%- if current_user.present? -%>
        {
          email: '<%= current_user.email %>',
          id: '<%= current_user.id %>',
        }
      <%- else -%>
        null
      <%- end -%>,
    };
  </script>
<% end %>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? "#{yield(:title)} | Release Maker" : "Release Maker"

    = render "layouts/sentry"
    = vite_client_tag
    link rel="preconnect" href="https://fonts.googleapis.com"
    link rel="preconnect" href="https://fonts.gstatic.com" crossorigin=true
    link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap"
    = vite_stylesheet_tag 'application.scss'
    = vite_javascript_tag 'application'
    = csrf_meta_tags

  body
    - if show_navigation?
      div.top-bar
        div.top-bar-left
          ul.dropdown.menu data-dropdown-menu=true
            li.menu-text Release Maker
            li = link_to "Projects", dashboard_path
        div.top-bar-right
          ul.menu
            li = link_to "Sign Out", sign_out_path, method: :delete
      div.expanded.row
        div.medium-12.large-12.columns
          == display_flash_messages
          == yield
    - else
      == yield